package DLMS;


/**
* DLMS/dlms.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DLMS.idl
* Saturday, December 5, 2015 3:49:24 PM EST
*/

public interface dlms extends dlmsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface dlms
